#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfxhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
for i in range(0, 100):
    name = input("What is your name: ")
    name = name.lower()
    office = {"jim": "Looks directly at the camera", 
            "pam": "Holding Jim's hand and laughing", 
            "dwight": "Cutting beets in the kitchen", 
            "micheal": "Yelling at Toby", 
            "oscar": "Dancing with Meredith",
            "erin": "Doing a handstand, showing Andy", 
            "kevin": "Sitting at table, hungry", 
            "jan": "Showing Kevin and Stanley her Serenity by Jan candles", 
            "andy": "Watching Erin's handstand", 
            "angela": "Pulling her brownies out of the oven", 
            "phyllis": "Taking a picture of the whole thing", 
            "toby": "Getting yelled at by Micheal", 
            "stanley": "Pouring a drink at table", 
            "ryan": "Giving Kelly a (forced) piggyback rid, annoyed", 
            "meredith": "Dancing with Oscar", 
            "kelly": "Talking alot on this piggyback ride", 
            "creed": "Stealing something, acting super shady"}
    if name in office.keys():
        print(office[name])
    else:
        print("Sorry, not right. Try Again.")

#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfxhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
#kfsdhjfksjfsjdhfksjfhksjfksjfhksjfksjfhksjfhksjfhksjfhksjfhksjfhksjfhksfjh
